# backend/DB/store_base.py
from __future__ import annotations
from typing import Iterable, Iterator, Optional, Protocol
from ..models import Sentence  # adjust if your models path differs

class CorpusStore(Protocol):
    def create(self, s: Sentence) -> None: ...
    def bulk_create(self, items: Iterable[Sentence]) -> int: ...
    def read(self, sid: int) -> Sentence: ...
    def read_many(self, ids: Iterable[int]) -> Iterator[Sentence]: ...
    def count(self) -> int: ...
    def update(
        self,
        sid: int,
        *,
        path: Optional[str]=None,
        line_no: Optional[int]=None,
        original: Optional[str]=None,
        normalized: Optional[str]=None,
        norm_to_orig: Optional[list[int]]=None,
    ) -> None: ...
    def delete(self, sid: int) -> None: ...
    def close(self) -> None: ...
